language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer require onethirtyone/repository-pattern
  - composer update
  - cd ./vendor/onethirtyone/repository-pattern/tests

script: "phpunit RepositoryTest.php"